//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Bill { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int Client_ID { get; set; }
        public int Cashiers_ID { get; set; }
    
        public virtual Cashiers Cashiers {private get; set; }
        public virtual Clients Clients { private get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { private get; set; }
    }
}
