//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetShopYP5Entities1 : DbContext
    {
        public PetShopYP5Entities1()
            : base("name=PetShopYP5Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<BreedOfPet> BreedOfPet { get; set; }
        public virtual DbSet<Cashiers> Cashiers { get; set; }
        public virtual DbSet<ClientCheck> ClientCheck { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<FoodForPets> FoodForPets { get; set; }
        public virtual DbSet<LoginPassword> LoginPassword { get; set; }
        public virtual DbSet<NaimenovaniePetsa> NaimenovaniePetsa { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Pets> Pets { get; set; }
        public virtual DbSet<Rolee> Rolee { get; set; }
        public virtual DbSet<ServicesForPet> ServicesForPet { get; set; }
        public virtual DbSet<Shelter> Shelter { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Toys> Toys { get; set; }
    }
}
