//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Pets_ID { get; set; }
        public int Employees_ID { get; set; }
        public int Toys_ID { get; set; }
        public int FoodForPets_ID { get; set; }
        public int Status_ID { get; set; }
        public int Bill_ID { get; set; }
    
        public virtual Bill Bill { private get; set; }
        public virtual Employees Employees { private get; set; }
        public virtual FoodForPets FoodForPets { private get; set; }
        public virtual Pets Pets { private get; set; }
        public virtual Statuses Statuses { private get; set; }
        public virtual Toys Toys { private get; set; }
    }
}
